name: update-playwright-snapshots

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who triggered this refresh (enter github username to tag yourself)?"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          npm install
          python -m pip install .
          python -m pip install jupyterlab
          npx playwright install
      - name: Install Playwright Browser
        run: npx playwright install-deps chromium
      - name: generate new snapshots and commit them
        run: |
          npx playwright test --update-snapshots
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "test: update tests snapshots"
          git push
